M48
; DRILL file {KiCad 9.0.2} date 2026-06-17T12:46:47+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-17T12:46:47+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.092
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X143.0Y-91.92
X143.0Y-94.46
X143.0Y-97.0
X143.0Y-99.54
T2
X128.95Y-95.675
X135.95Y-95.675
M30
