name: Deploy Jekyll site to Cloudflare Pages

on:
  push:
    branches:
      - "main"
    paths:
      - "docs/**"
      - ".github/workflows/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions
permissions:
  contents: read
  deployments: write

# Allow one concurrent deployment
concurrency:
  group: "cloudflare-pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          cache-version: 0
          working-directory: '${{ github.workspace }}/docs'

      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl ""
        env:
          JEKYLL_ENV: production

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: docs/_site/

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: cloudflare-pages
      url: httlps://sensedu-shield.com
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: site
          
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy site --project-name=sensedu --branch=main
